// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY5d6wQnEfqaSiPcG5wCCW-D8DHjcXmL0',
    appId: '1:60110885529:android:b34724f606fe5477fade08',
    messagingSenderId: '60110885529',
    projectId: 'bhashaapp-v3',
    databaseURL: 'https://bhashaapp-v3-default-rtdb.firebaseio.com',
    storageBucket: 'bhashaapp-v3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcQz0OBGAYwdtU9A7uo3KA_8_6BuXg3ao',
    appId: '1:60110885529:ios:c1b547eae600bb26fade08',
    messagingSenderId: '60110885529',
    projectId: 'bhashaapp-v3',
    databaseURL: 'https://bhashaapp-v3-default-rtdb.firebaseio.com',
    storageBucket: 'bhashaapp-v3.firebasestorage.app',
    androidClientId: '60110885529-gh62ntp2mnjtfbb0majlam2r2pjt9qas.apps.googleusercontent.com',
    iosClientId: '60110885529-gv8ainrmmnne8imll8pmod420mlm4uga.apps.googleusercontent.com',
    iosBundleId: 'com.bhashaapp.bhashaapp',
  );

}